name: NPM

# About this workflow:
# It is triggered on push events to branches production and testing. Then it performs a checkout of the current repo
# and sets up a node environment (v12). Following, it will run `npm ci` to build the package. Finally, the `npm
# publish` command will be run, when on branch testing it will run `npm publish --tag beta` to publish it under the
# beta flag on npm. Note: if the package version is not bumped manually the publish step will fail because we can not
# publish to an existing version (see the npm_version_bump_and_publish.yml workflow to solve this).

# Required secrets:
# - NPM_AUTH_TOKEN: required for publishing to npm
# - SLACK_WEBHOOK_URL: required for posting a message in #software

# Optional secrets:
# - SSH_KEY: if `npm ci` needs to install private npm packages

# Note: make sure to commit package-lock.json, this is needed for `npm ci`.

# Note: add `.github` to .npmignore

# Note: when publishing a scoped npm package (e.g. @athombv/node-my-package) append `--access public` to the `npm publish` command, by default scoped packages are published privately.
# For more information see: https://docs.npmjs.com/creating-and-publishing-an-org-scoped-package

# Defines the trigger for this action, in general you want it to run when pushing to production | testing. For more
# information see: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#about-workflow-events)
on:
  push:
    branches:
      no-branch
jobs:
  npm_publish:
    name: Publish

    runs-on: ubuntu-latest
    steps:

      # Checks out the current repository.
      - name: Checkout git repository
        uses: actions/checkout@v2

      # Configures a Node.js environment.
      - name: Set up node 12 environment
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          # Needed for publishing to npm
          registry-url: 'https://registry.npmjs.org'
          
      # Set the SSH key
      - uses: webfactory/ssh-agent@v0.4.1
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        if: env.SSH_KEY != null
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      # Run `npm ci` to re-create your local environment.
      - name: Build
        run: npm ci

      # Publish when this action is running on branch production (when publishing a scoped package add --access public)
      - name: Publish
        if: github.ref == 'refs/heads/production'
        run: |
          npm publish
          VERSION="$(node -p "require('./package.json').version")"
          echo package_version=${VERSION} >> $GITHUB_ENV
          echo $package_version
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      # Publish to beta when this action is running on branch testing (when publishing a scoped package add --access public)
      - name: Publish to beta
        if: github.ref == 'refs/heads/testing'
        run: |
          npm publish --tag beta
          VERSION="$(node -p "require('./package.json').version")@beta"
          echo package_version=${VERSION}@beta >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

       # Post a Slack notification in #software on success/failure
      - name: Slack notify
        if: always()
        uses: innocarpe/actions-slack@v1
        with:
          status: ${{ job.status }}
          success_text: '${{github.repository}} - published v${{env.package_version}} to npm 🚀'
          failure_text: '${{github.repository}} - failed to publish to npm'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Required
